using AlJourney.Scripts.Characters;
using AlJourney.Scripts.Core;

namespace AlJourney.Scripts.Battle
{
    /// <summary>
    /// Service for spawning enemies. As of Stage 3 (campaign map), wave composition is curated and
    /// defined in <see cref="Data.LevelDefinition.Waves"/> (see <see cref="Data.CampaignDatabase"/>)
    /// rather than generated by a formula based on wave number — this class only creates the requested
    /// creatures.
    /// </summary>
    public static class EnemySpawner
    {
        /// <summary>
        /// Helper method that spawns an enemy of the given type.
        /// </summary>
        public static Enemy SpawnEnemy(EnemyType type, int wave, int count = 1)
        {
            return Enemy.Create(type, wave, count);
        }
    }
}
