class_name EnemySpawner
extends RefCounted
## Service for spawning enemies. Wave composition is curated and defined in
## LevelDefinition.waves (see CampaignDatabase) rather than generated by a
## formula based on wave number — this class only creates the requested
## creatures.

## Helper method that spawns an enemy of the given type.
static func spawn_enemy(type: GameEnums.EnemyType, wave: int, count: int = 1) -> Enemy:
	return Enemy.create(type, wave, count)
